name: Deploy Backend and Frontend to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sapitos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          Backend/package-lock.json
          Frontend2/package-lock.json

    - name: Install backend dependencies
      run: |
        cd Backend
        npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend2
        npm ci

    - name: Build frontend
      run: |
        cd frontend2
        npm run build

    - name: Prepare backend for deployment
      run: |
        # Copy frontend build to backend public folder
        mkdir -p Backend/public
        cp -r frontend2/dist/* Backend/public/
        
        # Create web.config for Azure App Service (Node.js)
        cat > Backend/web.config << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="iisnode" path="index.js" verb="*" modules="iisnode"/>
            </handlers>
            <rewrite>
              <rules>
                <rule name="StaticContent">
                  <action type="Rewrite" url="public{REQUEST_URI}"/>
                </rule>
                <rule name="DynamicContent">
                  <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                  </conditions>
                  <action type="Rewrite" url="index.js"/>
                </rule>
              </rules>
            </rewrite>
            <iisnode watchedFiles="web.config;*.js"/>
          </system.webServer>
        </configuration>
        EOF

    - name: Clean previous deployment files
      run: |
        rm -f backend.zip
        
    - name: Zip backend
      run: |
        cd Backend
        zip -r ../backend.zip . -x "node_modules/*" ".env" "*.git*" ".env.*"
        
    - name: Deploy to Azure Web App via zipdeploy
      shell: bash
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_WEBAPP_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_WEBAPP_PASSWORD }}
        AZURE_APP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      run: |
        # Verificar que los secretos existen
        if [ -z "$AZURE_USERNAME" ] || [ -z "$AZURE_PASSWORD" ] || [ -z "$AZURE_APP_NAME" ]; then
          echo "Error: Missing required secrets" >&2
          echo "Please ensure AZURE_WEBAPP_USERNAME, AZURE_WEBAPP_PASSWORD, and AZURE_WEBAPP_NAME are set"
          exit 1
        fi
        
        echo "Deploying to app: $AZURE_APP_NAME"
        echo "Using username: $AZURE_USERNAME"
        
        # Realizar el despliegue
        echo "Starting deployment..."
        curl -X POST "https://${AZURE_APP_NAME}.scm.azurewebsites.net/api/zipdeploy" \
          --fail \
          --user "$AZURE_USERNAME:$AZURE_PASSWORD" \
          --data-binary "@backend.zip" \
          --header "Content-Type: application/zip" \
          --max-time 600 \
          -v \
          || { echo "Error: Deployment failed" >&2; exit 1; }

    - name: Verify deployment
      run: |
        echo "Deployment completed. Please check your Azure Web App at: https://sapitos.azurewebsites.net"